create table onl_cgform_head
(
    id                   varchar(32)                     not null comment '主键ID'
        primary key,
    table_name           varchar(50)                     not null comment '表名',
    table_type           int                             not null comment '表类型: 0单表、1主表、2附表',
    table_version        int         default 1           null comment '表版本',
    table_txt            varchar(200)                    not null comment '表说明',
    is_checkbox          varchar(5)                      not null comment '是否带checkbox',
    is_db_synch          varchar(20) default 'N'         not null comment '同步数据库状态',
    is_page              varchar(5)                      not null comment '是否分页',
    is_tree              varchar(5)                      not null comment '是否是树',
    id_sequence          varchar(200)                    null comment '主键生成序列',
    id_type              varchar(100)                    null comment '主键类型',
    query_mode           varchar(10)                     null comment '查询模式',
    relation_type        int                             null comment '映射关系 0一对多  1一对一',
    sub_table_str        varchar(1000)                   null comment '子表',
    tab_order_num        int                             null comment '附表排序序号',
    tree_parent_id_field varchar(50)                     null comment '树形表单父id',
    tree_id_field        varchar(50)                     null comment '树表主键字段',
    tree_fieldname       varchar(50)                     null comment '树开表单列字段',
    form_category        varchar(50) default 'bdfl_ptbd' not null comment '表单分类',
    form_template        varchar(50)                     null comment 'PC表单模板',
    form_template_mobile varchar(50)                     null comment '表单模板样式(移动端)',
    scroll               int         default 0           null comment '是否有横向滚动条',
    copy_version         int                             null comment '复制版本号',
    copy_type            int         default 0           null comment '复制表类型1为复制表 0为原始表',
    physic_id            varchar(32)                     null comment '原始表ID',
    ext_config_json      varchar(1000)                   null comment '扩展JSON',
    update_by            varchar(32)                     null comment '修改人',
    update_time          datetime                        null comment '修改时间',
    create_by            varchar(32)                     null comment '创建人',
    create_time          datetime                        null comment '创建时间',
    theme_template       varchar(50)                     null comment '主题模板',
    is_des_form          varchar(2)                      null comment '是否用设计器表单',
    des_form_code        varchar(50)                     null comment '设计器表单编码',
    low_app_id           varchar(32)                     null comment '关联的应用ID'
)
    charset = utf8;

create index idx_och_cgform_head_id
    on onl_cgform_head (table_name);

create index idx_och_form_template_mobile
    on onl_cgform_head (form_template_mobile);

create index idx_och_table_name
    on onl_cgform_head (form_template);

create index idx_och_table_version
    on onl_cgform_head (table_version);

INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('05a3a30dada7411c9109306aa4117068', 'test_note', 1, 12, '请假单@JS增强示例', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'temp', '1', null, 1, null, 0, null, '{"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":""}', 'admin', '2021-08-18 15:54:55', 'admin', '2020-05-06 11:34:31', 'normal', 'N', '', null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('09fd28e4b7184c1a9668496a5c496450', 'ces_order_customer', 3, 6, '订单客户', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', 1, 'ces_order_customer', 3, null, null, null, 'temp', '1', null, 1, null, 0, null, '{"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":""}', 'admin', '2022-05-07 19:05:57', 'admin', '2020-05-08 23:51:49', 'normal', 'N', '', null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('3d447fa919b64f6883a834036c14aa67', 'test_enhance_select', 1, 5, 'js增强实现下拉联动效果', 'N', 'Y', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'bdfl_include', '1', null, 0, null, 0, null, null, 'admin', '2020-02-21 17:58:46', 'admin', '2020-02-20 16:19:00', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('402880e570a5d7000170a5d700f50000', 'test_order_product$1', 1, 11, '订单产品明细', 'N', 'N', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'bdfl_include', '1', null, 0, 1, 1, 'deea5a8ec619460c9245ba85dbc59e80', null, null, null, 'admin', '2020-03-04 21:58:16', null, null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('402880e5721355dd01721355dd390000', 'ces_order_goods$1', 1, 1, '订单商品', 'Y', 'N', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'temp', '1', null, 1, 1, 1, '86bf17839a904636b7ed96201b2fa6ea', null, null, null, 'admin', '2020-05-14 21:18:14', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('402880eb71d61d3d0171d61d3de30000', 'demo_field_def_val_sub$1', 1, 2, '示例：控件默认值（子表）', 'Y', 'N', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'demo', '1', null, 1, 1, 1, '4fb8e12a697f4d5bbe9b9fb1e9009486', null, 'admin', '2020-05-03 00:54:16', 'admin', '2020-05-02 23:59:33', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('402881fd812267500181226750e90000', 'ces_shop_goods$1', 1, 1, '商品', 'Y', 'N', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'temp', '1', null, 1, 7, 1, '53a3e82b54b946c2b904f605875a275c', null, null, null, 'admin', '2022-06-02 11:13:25', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('402881fd812267500181226787d90001', 'test_note$1', 1, 2, '请假单@JS增强示例', 'Y', 'N', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'temp', '1', null, 1, 12, 1, '05a3a30dada7411c9109306aa4117068', '{"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":""}', 'admin', '2022-06-02 11:13:48', 'admin', '2022-06-02 11:13:39', 'normal', 'N', '', null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('402885e9812f585201812f5852920000', 'v3_hello$1', 1, 1, '第一个表单', 'Y', 'N', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'temp', '1', null, 1, 3, 1, '9ab817fd4c2e4e7ba6652c4fa46af389', '{"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":""}', null, null, 'admin', '2022-06-04 23:32:06', 'normal', 'N', '', null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('4adec929a6594108bef5b35ee9966e9f', 'demo_field_def_val_main', 2, 1, '示例：控件默认值（主表）', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', null, 'demo_field_def_val_sub', null, null, null, null, 'demo', '1', null, 1, null, 0, null, null, 'admin', '2020-11-26 17:28:14', 'admin', '2020-04-10 19:35:57', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('4fb8e12a697f4d5bbe9b9fb1e9009486', 'demo_field_def_val_sub', 3, 2, '示例：控件默认值（子表）', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'group', 0, null, 1, null, null, null, 'demo', '1', null, 1, null, 0, null, null, 'admin', '2020-11-26 17:28:14', 'admin', '2020-04-10 19:47:01', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('53a3e82b54b946c2b904f605875a275c', 'ces_shop_goods', 1, 7, '商品', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'temp', '1', null, 1, null, 0, null, null, 'admin', '2020-05-08 23:42:51', 'admin', '2020-05-07 22:49:47', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('56870166aba54ebfacb20ba6c770bd73', 'test_order_main', 2, 25, '测试订单主表', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', null, 'test_order_product', null, null, null, null, 'bdfl_include', '2', null, 0, null, 0, null, '{"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":""}', 'admin', '2022-07-26 22:50:10', 'admin', '2019-04-20 11:38:39', 'erp', 'N', '', null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('56efb74326e74064b60933f6f8af30ea', 'ces_order_main', 2, 9, '商城订单表', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', null, 'ces_order_goods,ces_order_customer', null, null, null, null, 'temp', '1', null, 1, null, 0, null, null, 'admin', '2022-05-07 19:05:57', 'admin', '2020-05-08 23:45:32', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('86bf17839a904636b7ed96201b2fa6ea', 'ces_order_goods', 3, 2, '订单商品', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', 0, null, 2, null, null, null, 'temp', '1', null, 1, null, 0, null, null, 'admin', '2020-05-14 21:18:49', 'admin', '2020-05-08 23:48:31', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('8d66ea41c7cc4ef9ab3aab9055657fc9', 'ces_shop_type', 1, 1, '商品分类', 'Y', 'Y', 'Y', 'Y', null, 'UUID', 'single', null, null, null, 'pid', 'has_child', 'name', 'temp', '1', null, 1, null, 0, null, null, 'admin', '2020-05-07 22:46:40', 'admin', '2020-05-07 22:46:31', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('997ee931515a4620bc30a9c1246429a9', 'test_shoptype_tree', 1, 2, '商品分类', 'Y', 'Y', 'Y', 'Y', null, 'UUID', 'single', null, null, null, 'pid', 'has_child', 'type_name', 'temp', '1', null, 1, null, 0, null, null, 'admin', '2020-05-03 00:57:47', 'admin', '2020-05-03 00:56:56', 'normal', null, null, null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('9ab817fd4c2e4e7ba6652c4fa46af389', 'v3_hello', 1, 3, '第一个表单', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'temp', '1', null, 1, null, 0, null, '{"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":""}', 'admin', '2022-06-04 23:20:55', 'admin', '2022-06-04 22:53:38', 'normal', 'N', '', null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('d0c0871f48f64288bb5683145b1572a7', 'v3_demo1', 1, 3, '第一个vue3例子', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'single', null, null, null, null, null, null, 'temp', '1', null, 1, null, 0, null, '{"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":""}', 'admin', '2022-06-02 15:39:31', 'admin', '2022-06-02 15:39:09', 'normal', 'N', '', null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('d35109c3632c4952a19ecc094943dd71', 'test_demo', 1, 35, '测试用户表', 'Y', 'Y', 'Y', 'N', null, 'UUID', 'group', null, null, null, null, null, null, 'bdfl_include', '2', null, 0, null, 0, null, '{"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":1200}', 'admin', '2021-08-18 15:53:31', 'admin', '2019-03-15 14:24:35', 'normal', 'N', '', null);
INSERT INTO onl_cgform_head (id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, form_template_mobile, scroll, copy_version, copy_type, physic_id, ext_config_json, update_by, update_time, create_by, create_time, theme_template, is_des_form, des_form_code, low_app_id) VALUES ('deea5a8ec619460c9245ba85dbc59e80', 'test_order_product', 3, 12, '订单产品明细', 'N', 'Y', 'Y', 'N', null, 'UUID', 'single', 0, null, 1, null, null, null, 'bdfl_include', '1', null, 0, null, 0, null, null, 'admin', '2020-05-03 01:01:18', 'admin', '2019-04-20 11:41:19', 'normal', null, null, null);
